//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServeurChat {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Message", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Message : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AuteurField;
        
        private System.DateTime CreationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Text {
            get {
                return this.TextField;
            }
            set {
                if ((object.ReferenceEquals(this.TextField, value) != true)) {
                    this.TextField = value;
                    this.RaisePropertyChanged("Text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Auteur {
            get {
                return this.AuteurField;
            }
            set {
                if ((object.ReferenceEquals(this.AuteurField, value) != true)) {
                    this.AuteurField = value;
                    this.RaisePropertyChanged("Auteur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime Creation {
            get {
                return this.CreationField;
            }
            set {
                if ((this.CreationField.Equals(value) != true)) {
                    this.CreationField = value;
                    this.RaisePropertyChanged("Creation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServeurChat.ServeurChatSoap")]
    public interface ServeurChatSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nick de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/LogIn", ReplyAction="*")]
        Client.ServeurChat.LogInResponse LogIn(Client.ServeurChat.LogInRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nick de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Register", ReplyAction="*")]
        Client.ServeurChat.RegisterResponse Register(Client.ServeurChat.RegisterRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nick de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        Client.ServeurChat.SendMessageResponse SendMessage(Client.ServeurChat.SendMessageRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nick de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendPrivateMessage", ReplyAction="*")]
        Client.ServeurChat.SendPrivateMessageResponse SendPrivateMessage(Client.ServeurChat.SendPrivateMessageRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nick de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveAllMessage", ReplyAction="*")]
        Client.ServeurChat.ReceiveAllMessageResponse ReceiveAllMessage(Client.ServeurChat.ReceiveAllMessageRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nick de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceiveMessageNonRead", ReplyAction="*")]
        Client.ServeurChat.ReceiveMessageNonReadResponse ReceiveMessageNonRead(Client.ServeurChat.ReceiveMessageNonReadRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément nick de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReceivePrivateMessage", ReplyAction="*")]
        Client.ServeurChat.ReceivePrivateMessageResponse ReceivePrivateMessage(Client.ServeurChat.ReceivePrivateMessageRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément oldnick de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangeNick", ReplyAction="*")]
        Client.ServeurChat.ChangeNickResponse ChangeNick(Client.ServeurChat.ChangeNickRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogIn", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.LogInRequestBody Body;
        
        public LogInRequest() {
        }
        
        public LogInRequest(Client.ServeurChat.LogInRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] nickhashed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int counter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] G;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] J;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] P;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public byte[] Q;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] Seed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public byte[] X;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public byte[] Y;
        
        public LogInRequestBody() {
        }
        
        public LogInRequestBody(string nick, string password, byte[] nickhashed, int counter, byte[] G, byte[] J, byte[] P, byte[] Q, byte[] Seed, byte[] X, byte[] Y) {
            this.nick = nick;
            this.password = password;
            this.nickhashed = nickhashed;
            this.counter = counter;
            this.G = G;
            this.J = J;
            this.P = P;
            this.Q = Q;
            this.Seed = Seed;
            this.X = X;
            this.Y = Y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LogInResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LogInResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.LogInResponseBody Body;
        
        public LogInResponse() {
        }
        
        public LogInResponse(Client.ServeurChat.LogInResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LogInResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool LogInResult;
        
        public LogInResponseBody() {
        }
        
        public LogInResponseBody(bool LogInResult) {
            this.LogInResult = LogInResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(Client.ServeurChat.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] nickhashed;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int counter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] G;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public byte[] J;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public byte[] P;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public byte[] Q;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] Seed;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public byte[] X;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public byte[] Y;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string nick, string password, byte[] nickhashed, int counter, byte[] G, byte[] J, byte[] P, byte[] Q, byte[] Seed, byte[] X, byte[] Y) {
            this.nick = nick;
            this.password = password;
            this.nickhashed = nickhashed;
            this.counter = counter;
            this.G = G;
            this.J = J;
            this.P = P;
            this.Q = Q;
            this.Seed = Seed;
            this.X = X;
            this.Y = Y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(Client.ServeurChat.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool RegisterResult;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(bool RegisterResult) {
            this.RegisterResult = RegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.SendMessageRequestBody Body;
        
        public SendMessageRequest() {
        }
        
        public SendMessageRequest(Client.ServeurChat.SendMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] messagehashed;
        
        public SendMessageRequestBody() {
        }
        
        public SendMessageRequestBody(string nick, string message, byte[] messagehashed) {
            this.nick = nick;
            this.message = message;
            this.messagehashed = messagehashed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.SendMessageResponseBody Body;
        
        public SendMessageResponse() {
        }
        
        public SendMessageResponse(Client.ServeurChat.SendMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendMessageResult;
        
        public SendMessageResponseBody() {
        }
        
        public SendMessageResponseBody(bool SendMessageResult) {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPrivateMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPrivateMessage", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.SendPrivateMessageRequestBody Body;
        
        public SendPrivateMessageRequest() {
        }
        
        public SendPrivateMessageRequest(Client.ServeurChat.SendPrivateMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendPrivateMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string recipient;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public byte[] messagehashed;
        
        public SendPrivateMessageRequestBody() {
        }
        
        public SendPrivateMessageRequestBody(string nick, string recipient, string message, byte[] messagehashed) {
            this.nick = nick;
            this.recipient = recipient;
            this.message = message;
            this.messagehashed = messagehashed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendPrivateMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendPrivateMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.SendPrivateMessageResponseBody Body;
        
        public SendPrivateMessageResponse() {
        }
        
        public SendPrivateMessageResponse(Client.ServeurChat.SendPrivateMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendPrivateMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool SendPrivateMessageResult;
        
        public SendPrivateMessageResponseBody() {
        }
        
        public SendPrivateMessageResponseBody(bool SendPrivateMessageResult) {
            this.SendPrivateMessageResult = SendPrivateMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveAllMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveAllMessage", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.ReceiveAllMessageRequestBody Body;
        
        public ReceiveAllMessageRequest() {
        }
        
        public ReceiveAllMessageRequest(Client.ServeurChat.ReceiveAllMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveAllMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] nickhashed;
        
        public ReceiveAllMessageRequestBody() {
        }
        
        public ReceiveAllMessageRequestBody(string nick, byte[] nickhashed) {
            this.nick = nick;
            this.nickhashed = nickhashed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveAllMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveAllMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.ReceiveAllMessageResponseBody Body;
        
        public ReceiveAllMessageResponse() {
        }
        
        public ReceiveAllMessageResponse(Client.ServeurChat.ReceiveAllMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveAllMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServeurChat.Message[] ReceiveAllMessageResult;
        
        public ReceiveAllMessageResponseBody() {
        }
        
        public ReceiveAllMessageResponseBody(Client.ServeurChat.Message[] ReceiveAllMessageResult) {
            this.ReceiveAllMessageResult = ReceiveAllMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMessageNonReadRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMessageNonRead", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.ReceiveMessageNonReadRequestBody Body;
        
        public ReceiveMessageNonReadRequest() {
        }
        
        public ReceiveMessageNonReadRequest(Client.ServeurChat.ReceiveMessageNonReadRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMessageNonReadRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] nickhashed;
        
        public ReceiveMessageNonReadRequestBody() {
        }
        
        public ReceiveMessageNonReadRequestBody(string nick, byte[] nickhashed) {
            this.nick = nick;
            this.nickhashed = nickhashed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceiveMessageNonReadResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceiveMessageNonReadResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.ReceiveMessageNonReadResponseBody Body;
        
        public ReceiveMessageNonReadResponse() {
        }
        
        public ReceiveMessageNonReadResponse(Client.ServeurChat.ReceiveMessageNonReadResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceiveMessageNonReadResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServeurChat.Message[] ReceiveMessageNonReadResult;
        
        public ReceiveMessageNonReadResponseBody() {
        }
        
        public ReceiveMessageNonReadResponseBody(Client.ServeurChat.Message[] ReceiveMessageNonReadResult) {
            this.ReceiveMessageNonReadResult = ReceiveMessageNonReadResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceivePrivateMessageRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceivePrivateMessage", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.ReceivePrivateMessageRequestBody Body;
        
        public ReceivePrivateMessageRequest() {
        }
        
        public ReceivePrivateMessageRequest(Client.ServeurChat.ReceivePrivateMessageRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceivePrivateMessageRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public byte[] nickhashed;
        
        public ReceivePrivateMessageRequestBody() {
        }
        
        public ReceivePrivateMessageRequestBody(string nick, byte[] nickhashed) {
            this.nick = nick;
            this.nickhashed = nickhashed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReceivePrivateMessageResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReceivePrivateMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.ReceivePrivateMessageResponseBody Body;
        
        public ReceivePrivateMessageResponse() {
        }
        
        public ReceivePrivateMessageResponse(Client.ServeurChat.ReceivePrivateMessageResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReceivePrivateMessageResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Client.ServeurChat.Message[] ReceivePrivateMessageResult;
        
        public ReceivePrivateMessageResponseBody() {
        }
        
        public ReceivePrivateMessageResponseBody(Client.ServeurChat.Message[] ReceivePrivateMessageResult) {
            this.ReceivePrivateMessageResult = ReceivePrivateMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeNickRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeNick", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.ChangeNickRequestBody Body;
        
        public ChangeNickRequest() {
        }
        
        public ChangeNickRequest(Client.ServeurChat.ChangeNickRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeNickRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string oldnick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newnick;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] newnickhashed;
        
        public ChangeNickRequestBody() {
        }
        
        public ChangeNickRequestBody(string oldnick, string newnick, byte[] newnickhashed) {
            this.oldnick = oldnick;
            this.newnick = newnick;
            this.newnickhashed = newnickhashed;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeNickResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeNickResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.ServeurChat.ChangeNickResponseBody Body;
        
        public ChangeNickResponse() {
        }
        
        public ChangeNickResponse(Client.ServeurChat.ChangeNickResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeNickResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangeNickResult;
        
        public ChangeNickResponseBody() {
        }
        
        public ChangeNickResponseBody(bool ChangeNickResult) {
            this.ChangeNickResult = ChangeNickResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServeurChatSoapChannel : Client.ServeurChat.ServeurChatSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServeurChatSoapClient : System.ServiceModel.ClientBase<Client.ServeurChat.ServeurChatSoap>, Client.ServeurChat.ServeurChatSoap {
        
        public ServeurChatSoapClient() {
        }
        
        public ServeurChatSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServeurChatSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServeurChatSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServeurChatSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServeurChat.LogInResponse Client.ServeurChat.ServeurChatSoap.LogIn(Client.ServeurChat.LogInRequest request) {
            return base.Channel.LogIn(request);
        }
        
        public bool LogIn(string nick, string password, byte[] nickhashed, int counter, byte[] G, byte[] J, byte[] P, byte[] Q, byte[] Seed, byte[] X, byte[] Y) {
            Client.ServeurChat.LogInRequest inValue = new Client.ServeurChat.LogInRequest();
            inValue.Body = new Client.ServeurChat.LogInRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.password = password;
            inValue.Body.nickhashed = nickhashed;
            inValue.Body.counter = counter;
            inValue.Body.G = G;
            inValue.Body.J = J;
            inValue.Body.P = P;
            inValue.Body.Q = Q;
            inValue.Body.Seed = Seed;
            inValue.Body.X = X;
            inValue.Body.Y = Y;
            Client.ServeurChat.LogInResponse retVal = ((Client.ServeurChat.ServeurChatSoap)(this)).LogIn(inValue);
            return retVal.Body.LogInResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServeurChat.RegisterResponse Client.ServeurChat.ServeurChatSoap.Register(Client.ServeurChat.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public bool Register(string nick, string password, byte[] nickhashed, int counter, byte[] G, byte[] J, byte[] P, byte[] Q, byte[] Seed, byte[] X, byte[] Y) {
            Client.ServeurChat.RegisterRequest inValue = new Client.ServeurChat.RegisterRequest();
            inValue.Body = new Client.ServeurChat.RegisterRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.password = password;
            inValue.Body.nickhashed = nickhashed;
            inValue.Body.counter = counter;
            inValue.Body.G = G;
            inValue.Body.J = J;
            inValue.Body.P = P;
            inValue.Body.Q = Q;
            inValue.Body.Seed = Seed;
            inValue.Body.X = X;
            inValue.Body.Y = Y;
            Client.ServeurChat.RegisterResponse retVal = ((Client.ServeurChat.ServeurChatSoap)(this)).Register(inValue);
            return retVal.Body.RegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServeurChat.SendMessageResponse Client.ServeurChat.ServeurChatSoap.SendMessage(Client.ServeurChat.SendMessageRequest request) {
            return base.Channel.SendMessage(request);
        }
        
        public bool SendMessage(string nick, string message, byte[] messagehashed) {
            Client.ServeurChat.SendMessageRequest inValue = new Client.ServeurChat.SendMessageRequest();
            inValue.Body = new Client.ServeurChat.SendMessageRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.message = message;
            inValue.Body.messagehashed = messagehashed;
            Client.ServeurChat.SendMessageResponse retVal = ((Client.ServeurChat.ServeurChatSoap)(this)).SendMessage(inValue);
            return retVal.Body.SendMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServeurChat.SendPrivateMessageResponse Client.ServeurChat.ServeurChatSoap.SendPrivateMessage(Client.ServeurChat.SendPrivateMessageRequest request) {
            return base.Channel.SendPrivateMessage(request);
        }
        
        public bool SendPrivateMessage(string nick, string recipient, string message, byte[] messagehashed) {
            Client.ServeurChat.SendPrivateMessageRequest inValue = new Client.ServeurChat.SendPrivateMessageRequest();
            inValue.Body = new Client.ServeurChat.SendPrivateMessageRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.recipient = recipient;
            inValue.Body.message = message;
            inValue.Body.messagehashed = messagehashed;
            Client.ServeurChat.SendPrivateMessageResponse retVal = ((Client.ServeurChat.ServeurChatSoap)(this)).SendPrivateMessage(inValue);
            return retVal.Body.SendPrivateMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServeurChat.ReceiveAllMessageResponse Client.ServeurChat.ServeurChatSoap.ReceiveAllMessage(Client.ServeurChat.ReceiveAllMessageRequest request) {
            return base.Channel.ReceiveAllMessage(request);
        }
        
        public Client.ServeurChat.Message[] ReceiveAllMessage(string nick, byte[] nickhashed) {
            Client.ServeurChat.ReceiveAllMessageRequest inValue = new Client.ServeurChat.ReceiveAllMessageRequest();
            inValue.Body = new Client.ServeurChat.ReceiveAllMessageRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.nickhashed = nickhashed;
            Client.ServeurChat.ReceiveAllMessageResponse retVal = ((Client.ServeurChat.ServeurChatSoap)(this)).ReceiveAllMessage(inValue);
            return retVal.Body.ReceiveAllMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServeurChat.ReceiveMessageNonReadResponse Client.ServeurChat.ServeurChatSoap.ReceiveMessageNonRead(Client.ServeurChat.ReceiveMessageNonReadRequest request) {
            return base.Channel.ReceiveMessageNonRead(request);
        }
        
        public Client.ServeurChat.Message[] ReceiveMessageNonRead(string nick, byte[] nickhashed) {
            Client.ServeurChat.ReceiveMessageNonReadRequest inValue = new Client.ServeurChat.ReceiveMessageNonReadRequest();
            inValue.Body = new Client.ServeurChat.ReceiveMessageNonReadRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.nickhashed = nickhashed;
            Client.ServeurChat.ReceiveMessageNonReadResponse retVal = ((Client.ServeurChat.ServeurChatSoap)(this)).ReceiveMessageNonRead(inValue);
            return retVal.Body.ReceiveMessageNonReadResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServeurChat.ReceivePrivateMessageResponse Client.ServeurChat.ServeurChatSoap.ReceivePrivateMessage(Client.ServeurChat.ReceivePrivateMessageRequest request) {
            return base.Channel.ReceivePrivateMessage(request);
        }
        
        public Client.ServeurChat.Message[] ReceivePrivateMessage(string nick, byte[] nickhashed) {
            Client.ServeurChat.ReceivePrivateMessageRequest inValue = new Client.ServeurChat.ReceivePrivateMessageRequest();
            inValue.Body = new Client.ServeurChat.ReceivePrivateMessageRequestBody();
            inValue.Body.nick = nick;
            inValue.Body.nickhashed = nickhashed;
            Client.ServeurChat.ReceivePrivateMessageResponse retVal = ((Client.ServeurChat.ServeurChatSoap)(this)).ReceivePrivateMessage(inValue);
            return retVal.Body.ReceivePrivateMessageResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServeurChat.ChangeNickResponse Client.ServeurChat.ServeurChatSoap.ChangeNick(Client.ServeurChat.ChangeNickRequest request) {
            return base.Channel.ChangeNick(request);
        }
        
        public bool ChangeNick(string oldnick, string newnick, byte[] newnickhashed) {
            Client.ServeurChat.ChangeNickRequest inValue = new Client.ServeurChat.ChangeNickRequest();
            inValue.Body = new Client.ServeurChat.ChangeNickRequestBody();
            inValue.Body.oldnick = oldnick;
            inValue.Body.newnick = newnick;
            inValue.Body.newnickhashed = newnickhashed;
            Client.ServeurChat.ChangeNickResponse retVal = ((Client.ServeurChat.ServeurChatSoap)(this)).ChangeNick(inValue);
            return retVal.Body.ChangeNickResult;
        }
    }
}
