//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTest.ServiceIsimaBook {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTest.ServiceIsimaBook.Author WriterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTest.ServiceIsimaBook.Editor PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private UnitTest.ServiceIsimaBook.Kind TypeField;
        
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReleaseDateField, value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public UnitTest.ServiceIsimaBook.Author Writer {
            get {
                return this.WriterField;
            }
            set {
                if ((object.ReferenceEquals(this.WriterField, value) != true)) {
                    this.WriterField = value;
                    this.RaisePropertyChanged("Writer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public UnitTest.ServiceIsimaBook.Editor Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public UnitTest.ServiceIsimaBook.Kind Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Author : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Editor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Editor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kind", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Kind : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ContactDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Zipcode {
            get {
                return this.ZipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipcodeField, value) != true)) {
                    this.ZipcodeField = value;
                    this.RaisePropertyChanged("Zipcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Currency", Namespace="http://www.webserviceX.NET/")]
    public enum Currency : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AFA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DZD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AWG = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUD = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BSD = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BHD = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BDT = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BBD = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BZD = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BMD = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BTN = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOB = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BWP = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BRL = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GBP = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BND = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIF = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XOF = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAF = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KHR = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAD = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CVE = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KYD = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLP = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNY = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COP = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KMF = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRC = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRK = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUP = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CYP = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CZK = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DKK = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DJF = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOP = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XCD = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EGP = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SVC = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EEK = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETB = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EUR = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FKP = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMD = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GHC = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GIP = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAU = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GTQ = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GNF = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GYD = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HTG = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HNL = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HKD = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HUF = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISK = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INR = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IDR = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IQD = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILS = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JMD = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JPY = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JOD = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KZT = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KES = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KRW = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KWD = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LAK = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LVL = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LBP = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LSL = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LRD = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LYD = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LTL = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOP = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MKD = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MGF = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MWK = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MYR = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MVR = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTL = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MRO = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUR = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MXN = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MDL = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNT = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAD = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MZM = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MMK = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NAD = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NPR = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANG = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NZD = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NIO = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NGN = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KPW = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOK = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OMR = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPF = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PKR = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPD = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAB = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PGK = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PYG = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PEN = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHP = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPT = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLN = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QAR = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROL = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUB = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WST = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STD = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAR = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCR = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SLL = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAG = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SGD = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SKK = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIT = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SBD = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOS = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZAR = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LKR = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHP = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SDD = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SRG = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SZL = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEK = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHF = 129,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYP = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TWD = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TZS = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THB = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOP = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TTD = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TND = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRL = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USD = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AED = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UGX = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UAH = 141,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UYU = 142,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VUV = 143,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VEB = 144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VND = 145,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YER = 146,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YUM = 147,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZMK = 148,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZWD = 149,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRY = 150,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceIsimaBook.ServiceIsimaBookSoap")]
    public interface ServiceIsimaBookSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        UnitTest.ServiceIsimaBook.HelloWorldResponse HelloWorld(UnitTest.ServiceIsimaBook.HelloWorldRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément books de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterOrder", ReplyAction="*")]
        UnitTest.ServiceIsimaBook.RegisterOrderResponse RegisterOrder(UnitTest.ServiceIsimaBook.RegisterOrderRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément creditcard de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyCreditCard", ReplyAction="*")]
        UnitTest.ServiceIsimaBook.VerifyCreditCardResponse VerifyCreditCard(UnitTest.ServiceIsimaBook.VerifyCreditCardRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément AllBooksResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllBooks", ReplyAction="*")]
        UnitTest.ServiceIsimaBook.AllBooksResponse AllBooks(UnitTest.ServiceIsimaBook.AllBooksRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertEuroTo", ReplyAction="*")]
        double ConvertEuroTo(double europrice, UnitTest.ServiceIsimaBook.Currency exchange);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.ServiceIsimaBook.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(UnitTest.ServiceIsimaBook.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.ServiceIsimaBook.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(UnitTest.ServiceIsimaBook.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterOrder", Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.ServiceIsimaBook.RegisterOrderRequestBody Body;
        
        public RegisterOrderRequest() {
        }
        
        public RegisterOrderRequest(UnitTest.ServiceIsimaBook.RegisterOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTest.ServiceIsimaBook.Book[] books;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string creditcard;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public UnitTest.ServiceIsimaBook.ContactDetails shipping;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public UnitTest.ServiceIsimaBook.ContactDetails invoicing;
        
        public RegisterOrderRequestBody() {
        }
        
        public RegisterOrderRequestBody(UnitTest.ServiceIsimaBook.Book[] books, string creditcard, UnitTest.ServiceIsimaBook.ContactDetails shipping, UnitTest.ServiceIsimaBook.ContactDetails invoicing) {
            this.books = books;
            this.creditcard = creditcard;
            this.shipping = shipping;
            this.invoicing = invoicing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.ServiceIsimaBook.RegisterOrderResponseBody Body;
        
        public RegisterOrderResponse() {
        }
        
        public RegisterOrderResponse(UnitTest.ServiceIsimaBook.RegisterOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterOrderResult;
        
        public RegisterOrderResponseBody() {
        }
        
        public RegisterOrderResponseBody(string RegisterOrderResult) {
            this.RegisterOrderResult = RegisterOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCreditCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyCreditCard", Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.ServiceIsimaBook.VerifyCreditCardRequestBody Body;
        
        public VerifyCreditCardRequest() {
        }
        
        public VerifyCreditCardRequest(UnitTest.ServiceIsimaBook.VerifyCreditCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyCreditCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string creditcard;
        
        public VerifyCreditCardRequestBody() {
        }
        
        public VerifyCreditCardRequestBody(string creditcard) {
            this.creditcard = creditcard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCreditCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyCreditCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.ServiceIsimaBook.VerifyCreditCardResponseBody Body;
        
        public VerifyCreditCardResponse() {
        }
        
        public VerifyCreditCardResponse(UnitTest.ServiceIsimaBook.VerifyCreditCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyCreditCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyCreditCardResult;
        
        public VerifyCreditCardResponseBody() {
        }
        
        public VerifyCreditCardResponseBody(bool VerifyCreditCardResult) {
            this.VerifyCreditCardResult = VerifyCreditCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllBooks", Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.ServiceIsimaBook.AllBooksRequestBody Body;
        
        public AllBooksRequest() {
        }
        
        public AllBooksRequest(UnitTest.ServiceIsimaBook.AllBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllBooksRequestBody {
        
        public AllBooksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllBooksResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTest.ServiceIsimaBook.AllBooksResponseBody Body;
        
        public AllBooksResponse() {
        }
        
        public AllBooksResponse(UnitTest.ServiceIsimaBook.AllBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllBooksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public UnitTest.ServiceIsimaBook.Book[] AllBooksResult;
        
        public AllBooksResponseBody() {
        }
        
        public AllBooksResponseBody(UnitTest.ServiceIsimaBook.Book[] AllBooksResult) {
            this.AllBooksResult = AllBooksResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceIsimaBookSoapChannel : UnitTest.ServiceIsimaBook.ServiceIsimaBookSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceIsimaBookSoapClient : System.ServiceModel.ClientBase<UnitTest.ServiceIsimaBook.ServiceIsimaBookSoap>, UnitTest.ServiceIsimaBook.ServiceIsimaBookSoap {
        
        public ServiceIsimaBookSoapClient() {
        }
        
        public ServiceIsimaBookSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceIsimaBookSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIsimaBookSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIsimaBookSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.ServiceIsimaBook.HelloWorldResponse UnitTest.ServiceIsimaBook.ServiceIsimaBookSoap.HelloWorld(UnitTest.ServiceIsimaBook.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            UnitTest.ServiceIsimaBook.HelloWorldRequest inValue = new UnitTest.ServiceIsimaBook.HelloWorldRequest();
            inValue.Body = new UnitTest.ServiceIsimaBook.HelloWorldRequestBody();
            UnitTest.ServiceIsimaBook.HelloWorldResponse retVal = ((UnitTest.ServiceIsimaBook.ServiceIsimaBookSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.ServiceIsimaBook.RegisterOrderResponse UnitTest.ServiceIsimaBook.ServiceIsimaBookSoap.RegisterOrder(UnitTest.ServiceIsimaBook.RegisterOrderRequest request) {
            return base.Channel.RegisterOrder(request);
        }
        
        public string RegisterOrder(UnitTest.ServiceIsimaBook.Book[] books, string creditcard, UnitTest.ServiceIsimaBook.ContactDetails shipping, UnitTest.ServiceIsimaBook.ContactDetails invoicing) {
            UnitTest.ServiceIsimaBook.RegisterOrderRequest inValue = new UnitTest.ServiceIsimaBook.RegisterOrderRequest();
            inValue.Body = new UnitTest.ServiceIsimaBook.RegisterOrderRequestBody();
            inValue.Body.books = books;
            inValue.Body.creditcard = creditcard;
            inValue.Body.shipping = shipping;
            inValue.Body.invoicing = invoicing;
            UnitTest.ServiceIsimaBook.RegisterOrderResponse retVal = ((UnitTest.ServiceIsimaBook.ServiceIsimaBookSoap)(this)).RegisterOrder(inValue);
            return retVal.Body.RegisterOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.ServiceIsimaBook.VerifyCreditCardResponse UnitTest.ServiceIsimaBook.ServiceIsimaBookSoap.VerifyCreditCard(UnitTest.ServiceIsimaBook.VerifyCreditCardRequest request) {
            return base.Channel.VerifyCreditCard(request);
        }
        
        public bool VerifyCreditCard(string creditcard) {
            UnitTest.ServiceIsimaBook.VerifyCreditCardRequest inValue = new UnitTest.ServiceIsimaBook.VerifyCreditCardRequest();
            inValue.Body = new UnitTest.ServiceIsimaBook.VerifyCreditCardRequestBody();
            inValue.Body.creditcard = creditcard;
            UnitTest.ServiceIsimaBook.VerifyCreditCardResponse retVal = ((UnitTest.ServiceIsimaBook.ServiceIsimaBookSoap)(this)).VerifyCreditCard(inValue);
            return retVal.Body.VerifyCreditCardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTest.ServiceIsimaBook.AllBooksResponse UnitTest.ServiceIsimaBook.ServiceIsimaBookSoap.AllBooks(UnitTest.ServiceIsimaBook.AllBooksRequest request) {
            return base.Channel.AllBooks(request);
        }
        
        public UnitTest.ServiceIsimaBook.Book[] AllBooks() {
            UnitTest.ServiceIsimaBook.AllBooksRequest inValue = new UnitTest.ServiceIsimaBook.AllBooksRequest();
            inValue.Body = new UnitTest.ServiceIsimaBook.AllBooksRequestBody();
            UnitTest.ServiceIsimaBook.AllBooksResponse retVal = ((UnitTest.ServiceIsimaBook.ServiceIsimaBookSoap)(this)).AllBooks(inValue);
            return retVal.Body.AllBooksResult;
        }
        
        public double ConvertEuroTo(double europrice, UnitTest.ServiceIsimaBook.Currency exchange) {
            return base.Channel.ConvertEuroTo(europrice, exchange);
        }
    }
}
