;  ASM code generated by mikroVirtualMachine for PIC - V. 8.2.0.0
;  Date/Time: 15/11/2010 09:12:39
;  Info: http://www.mikroe.com


; ADDRESS	OPCODE	ASM
; ----------------------------------------------
$0000	$28F7			GOTO	_main
$0139	$	_AFF1:
;bibliotheque.c,93 :: 		void AFF1(unsigned short Value)
;bibliotheque.c,95 :: 		PORTA = 1;
$0139	$3001			MOVLW	1
$013A	$1303			BCF	STATUS, RP1
$013B	$1283			BCF	STATUS, RP0
$013C	$0085			MOVWF	PORTA
;bibliotheque.c,96 :: 		PORTD = Value;
$013D	$0827			MOVF	FARG_AFF1+0, 0
$013E	$0088			MOVWF	PORTD
;bibliotheque.c,97 :: 		}
$013F	$0008			RETURN
$006D	$	_DEC2AFF:
;bibliotheque.c,14 :: 		unsigned short DEC2AFF(unsigned short NombreDecimal) {
;bibliotheque.c,15 :: 		switch (NombreDecimal) {
$006D	$28A8			GOTO	L_DEC2AFF_0
;bibliotheque.c,16 :: 		case 0 : return 0x3F;
$006E	$	L_DEC2AFF_2:
$006E	$303F			MOVLW	63
$006F	$1303			BCF	STATUS, RP1
$0070	$1283			BCF	STATUS, RP0
$0071	$00F0			MOVWF	STACK_0
$0072	$0008			RETURN
;bibliotheque.c,17 :: 		case 1 : return 0x06;
$0073	$	L_DEC2AFF_3:
$0073	$3006			MOVLW	6
$0074	$00F0			MOVWF	STACK_0
$0075	$0008			RETURN
;bibliotheque.c,18 :: 		case 2 : return 0x5B;
$0076	$	L_DEC2AFF_4:
$0076	$305B			MOVLW	91
$0077	$00F0			MOVWF	STACK_0
$0078	$0008			RETURN
;bibliotheque.c,19 :: 		case 3 : return 0x4F;
$0079	$	L_DEC2AFF_5:
$0079	$304F			MOVLW	79
$007A	$00F0			MOVWF	STACK_0
$007B	$0008			RETURN
;bibliotheque.c,20 :: 		case 4 : return 0x66;
$007C	$	L_DEC2AFF_6:
$007C	$3066			MOVLW	102
$007D	$00F0			MOVWF	STACK_0
$007E	$0008			RETURN
;bibliotheque.c,21 :: 		case 5 : return 0x6D;
$007F	$	L_DEC2AFF_7:
$007F	$306D			MOVLW	109
$0080	$00F0			MOVWF	STACK_0
$0081	$0008			RETURN
;bibliotheque.c,22 :: 		case 6 : return 0x7D;
$0082	$	L_DEC2AFF_8:
$0082	$307D			MOVLW	125
$0083	$00F0			MOVWF	STACK_0
$0084	$0008			RETURN
;bibliotheque.c,23 :: 		case 7 : return 0x07;
$0085	$	L_DEC2AFF_9:
$0085	$3007			MOVLW	7
$0086	$00F0			MOVWF	STACK_0
$0087	$0008			RETURN
;bibliotheque.c,24 :: 		case 8 : return 0x7F;
$0088	$	L_DEC2AFF_10:
$0088	$307F			MOVLW	127
$0089	$00F0			MOVWF	STACK_0
$008A	$0008			RETURN
;bibliotheque.c,25 :: 		case 9 : return 0x6F;
$008B	$	L_DEC2AFF_11:
$008B	$306F			MOVLW	111
$008C	$00F0			MOVWF	STACK_0
$008D	$0008			RETURN
;bibliotheque.c,26 :: 		case 10: return 0x77;//A
$008E	$	L_DEC2AFF_12:
$008E	$3077			MOVLW	119
$008F	$00F0			MOVWF	STACK_0
$0090	$0008			RETURN
;bibliotheque.c,27 :: 		case 11: return 0x7C;//b
$0091	$	L_DEC2AFF_13:
$0091	$307C			MOVLW	124
$0092	$00F0			MOVWF	STACK_0
$0093	$0008			RETURN
;bibliotheque.c,28 :: 		case 12: return 0x58;//c
$0094	$	L_DEC2AFF_14:
$0094	$3058			MOVLW	88
$0095	$00F0			MOVWF	STACK_0
$0096	$0008			RETURN
;bibliotheque.c,29 :: 		case 13: return 0x5E;//d
$0097	$	L_DEC2AFF_15:
$0097	$305E			MOVLW	94
$0098	$00F0			MOVWF	STACK_0
$0099	$0008			RETURN
;bibliotheque.c,30 :: 		case 15: return 0x79;//E
$009A	$	L_DEC2AFF_16:
$009A	$3079			MOVLW	121
$009B	$00F0			MOVWF	STACK_0
$009C	$0008			RETURN
;bibliotheque.c,31 :: 		case 16: return 0x71;//F
$009D	$	L_DEC2AFF_17:
$009D	$3071			MOVLW	113
$009E	$00F0			MOVWF	STACK_0
$009F	$0008			RETURN
;bibliotheque.c,32 :: 		case 17: return 0x78; //t
$00A0	$	L_DEC2AFF_18:
$00A0	$3078			MOVLW	120
$00A1	$00F0			MOVWF	STACK_0
$00A2	$0008			RETURN
;bibliotheque.c,33 :: 		case 18: return 0x5C; //o
$00A3	$	L_DEC2AFF_19:
$00A3	$305C			MOVLW	92
$00A4	$00F0			MOVWF	STACK_0
$00A5	$0008			RETURN
;bibliotheque.c,34 :: 		case 19: return 0x00; //" "
$00A6	$	L_DEC2AFF_20:
$00A6	$01F0			CLRF	STACK_0, 1
$00A7	$0008			RETURN
;bibliotheque.c,35 :: 		}
$00A8	$	L_DEC2AFF_0:
$00A8	$1303			BCF	STATUS, RP1
$00A9	$1283			BCF	STATUS, RP0
$00AA	$0827			MOVF	FARG_DEC2AFF+0, 0
$00AB	$3A00			XORLW	0
$00AC	$1903			BTFSC	STATUS, Z
$00AD	$286E			GOTO	L_DEC2AFF_2
$00AE	$0827			MOVF	FARG_DEC2AFF+0, 0
$00AF	$3A01			XORLW	1
$00B0	$1903			BTFSC	STATUS, Z
$00B1	$2873			GOTO	L_DEC2AFF_3
$00B2	$0827			MOVF	FARG_DEC2AFF+0, 0
$00B3	$3A02			XORLW	2
$00B4	$1903			BTFSC	STATUS, Z
$00B5	$2876			GOTO	L_DEC2AFF_4
$00B6	$0827			MOVF	FARG_DEC2AFF+0, 0
$00B7	$3A03			XORLW	3
$00B8	$1903			BTFSC	STATUS, Z
$00B9	$2879			GOTO	L_DEC2AFF_5
$00BA	$0827			MOVF	FARG_DEC2AFF+0, 0
$00BB	$3A04			XORLW	4
$00BC	$1903			BTFSC	STATUS, Z
$00BD	$287C			GOTO	L_DEC2AFF_6
$00BE	$0827			MOVF	FARG_DEC2AFF+0, 0
$00BF	$3A05			XORLW	5
$00C0	$1903			BTFSC	STATUS, Z
$00C1	$287F			GOTO	L_DEC2AFF_7
$00C2	$0827			MOVF	FARG_DEC2AFF+0, 0
$00C3	$3A06			XORLW	6
$00C4	$1903			BTFSC	STATUS, Z
$00C5	$2882			GOTO	L_DEC2AFF_8
$00C6	$0827			MOVF	FARG_DEC2AFF+0, 0
$00C7	$3A07			XORLW	7
$00C8	$1903			BTFSC	STATUS, Z
$00C9	$2885			GOTO	L_DEC2AFF_9
$00CA	$0827			MOVF	FARG_DEC2AFF+0, 0
$00CB	$3A08			XORLW	8
$00CC	$1903			BTFSC	STATUS, Z
$00CD	$2888			GOTO	L_DEC2AFF_10
$00CE	$0827			MOVF	FARG_DEC2AFF+0, 0
$00CF	$3A09			XORLW	9
$00D0	$1903			BTFSC	STATUS, Z
$00D1	$288B			GOTO	L_DEC2AFF_11
$00D2	$0827			MOVF	FARG_DEC2AFF+0, 0
$00D3	$3A0A			XORLW	10
$00D4	$1903			BTFSC	STATUS, Z
$00D5	$288E			GOTO	L_DEC2AFF_12
$00D6	$0827			MOVF	FARG_DEC2AFF+0, 0
$00D7	$3A0B			XORLW	11
$00D8	$1903			BTFSC	STATUS, Z
$00D9	$2891			GOTO	L_DEC2AFF_13
$00DA	$0827			MOVF	FARG_DEC2AFF+0, 0
$00DB	$3A0C			XORLW	12
$00DC	$1903			BTFSC	STATUS, Z
$00DD	$2894			GOTO	L_DEC2AFF_14
$00DE	$0827			MOVF	FARG_DEC2AFF+0, 0
$00DF	$3A0D			XORLW	13
$00E0	$1903			BTFSC	STATUS, Z
$00E1	$2897			GOTO	L_DEC2AFF_15
$00E2	$0827			MOVF	FARG_DEC2AFF+0, 0
$00E3	$3A0F			XORLW	15
$00E4	$1903			BTFSC	STATUS, Z
$00E5	$289A			GOTO	L_DEC2AFF_16
$00E6	$0827			MOVF	FARG_DEC2AFF+0, 0
$00E7	$3A10			XORLW	16
$00E8	$1903			BTFSC	STATUS, Z
$00E9	$289D			GOTO	L_DEC2AFF_17
$00EA	$0827			MOVF	FARG_DEC2AFF+0, 0
$00EB	$3A11			XORLW	17
$00EC	$1903			BTFSC	STATUS, Z
$00ED	$28A0			GOTO	L_DEC2AFF_18
$00EE	$0827			MOVF	FARG_DEC2AFF+0, 0
$00EF	$3A12			XORLW	18
$00F0	$1903			BTFSC	STATUS, Z
$00F1	$28A3			GOTO	L_DEC2AFF_19
$00F2	$0827			MOVF	FARG_DEC2AFF+0, 0
$00F3	$3A13			XORLW	19
$00F4	$1903			BTFSC	STATUS, Z
$00F5	$28A6			GOTO	L_DEC2AFF_20
$00F6	$	L_DEC2AFF_1:
;bibliotheque.c,36 :: 		}
$00F6	$0008			RETURN
$0132	$	_AFF2:
;bibliotheque.c,99 :: 		void AFF2(unsigned short Value)
;bibliotheque.c,101 :: 		PORTA = 2;
$0132	$3002			MOVLW	2
$0133	$1303			BCF	STATUS, RP1
$0134	$1283			BCF	STATUS, RP0
$0135	$0085			MOVWF	PORTA
;bibliotheque.c,102 :: 		PORTD = Value;
$0136	$0827			MOVF	FARG_AFF2+0, 0
$0137	$0088			MOVWF	PORTD
;bibliotheque.c,103 :: 		}
$0138	$0008			RETURN
$0140	$	_AFF3:
;bibliotheque.c,105 :: 		void AFF3(unsigned short Value)
;bibliotheque.c,107 :: 		PORTA = 4;
$0140	$3004			MOVLW	4
$0141	$1303			BCF	STATUS, RP1
$0142	$1283			BCF	STATUS, RP0
$0143	$0085			MOVWF	PORTA
;bibliotheque.c,108 :: 		PORTD = Value;
$0144	$0827			MOVF	FARG_AFF3+0, 0
$0145	$0088			MOVWF	PORTD
;bibliotheque.c,109 :: 		}
$0146	$0008			RETURN
$0117	$	_Div_8x8_U:
$0117	$1303			BCF	STATUS, RP1
$0118	$1283			BCF	STATUS, RP0
$0119	$01F8			CLRF	STACK_8, F
$011A	$3008			MOVLW	8
$011B	$00FC			MOVWF	STACK_12
$011C	$0D70			RLF	STACK_0, W
$011D	$0DF8			RLF	STACK_8, F
$011E	$0874			MOVF	STACK_4, W
$011F	$02F8			SUBWF	STACK_8, F
$0120	$1803			BTFSC	STATUS, C
$0121	$2924			GOTO	$+3
$0122	$07F8			ADDWF	STACK_8, F
$0123	$1003			BCF	STATUS, C
$0124	$0DF0			RLF	STACK_0, F
$0125	$0BFC			DECFSZ	STACK_12, F
$0126	$291C			GOTO	$-10
$0127	$0008			RETURN
$0004	$	_interrupt:
$0004	$00FF			MOVWF	STACK_15
$0005	$0E03			SWAPF	STATUS, 0
$0006	$0183			CLRF	STATUS
$0007	$00A5			MOVWF	?saveSTATUS
$0008	$0804			MOVF	FSR, 0
$0009	$00A4			MOVWF	?saveFSR
$000A	$080A			MOVF	PCLATH, 0
$000B	$00A6			MOVWF	?savePCLATH
$000C	$018A			CLRF	PCLATH
$000D	$0870			MOVF	STACK_0, 0
$000E	$00A9			MOVWF	STSAVED_0
;tp4corig.c,38 :: 		void interrupt() {
;tp4corig.c,39 :: 		if (INTCON.TMR0IF) { // IT provenant du TMR0
$000F	$1D0B			BTFSS	INTCON, 2
$0010	$285B			GOTO	L_interrupt_0
;tp4corig.c,40 :: 		Compteur_Temps++;
$0011	$0AA0			INCF	_Compteur_Temps, 1
;tp4corig.c,41 :: 		TMR0 = 0x20;
$0012	$3020			MOVLW	32
$0013	$0081			MOVWF	TMR0
;tp4corig.c,42 :: 		INTCON.TMR0IF=0;
$0014	$110B			BCF	INTCON, 2
;tp4corig.c,43 :: 		INTCON.TMR0IE=1;
$0015	$168B			BSF	INTCON, 5
;tp4corig.c,46 :: 		Numero_Afficheur_Rafraichi++;
$0016	$0AA1			INCF	_Numero_Afficheur_Rafraichi, 1
;tp4corig.c,47 :: 		switch( Numero_Afficheur_Rafraichi)
$0017	$284B			GOTO	L_interrupt_1
;tp4corig.c,49 :: 		case 4: Numero_Afficheur_Rafraichi=1;
$0018	$	L_interrupt_3:
$0018	$3001			MOVLW	1
$0019	$00A1			MOVWF	_Numero_Afficheur_Rafraichi
;tp4corig.c,50 :: 		case 1: AFF1(DEC2AFF(Compteur_Bouton%10));break;
$001A	$	L_interrupt_4:
$001A	$300A			MOVLW	10
$001B	$00F4			MOVWF	STACK_4
$001C	$0822			MOVF	_Compteur_Bouton, 0
$001D	$00F0			MOVWF	STACK_0
$001E	$2117			CALL	_div_8x8_u
$001F	$0878			MOVF	STACK_8, 0
$0020	$00F0			MOVWF	STACK_0
$0021	$0870			MOVF	STACK_0, 0
$0022	$00A7			MOVWF	FARG_DEC2AFF+0
$0023	$206D			CALL	_DEC2AFF
$0024	$1303			BCF	STATUS, RP1
$0025	$1283			BCF	STATUS, RP0
$0026	$0870			MOVF	STACK_0, 0
$0027	$00A7			MOVWF	FARG_AFF1+0
$0028	$2139			CALL	_AFF1
$0029	$285B			GOTO	L_interrupt_2
;tp4corig.c,51 :: 		case 2: AFF2(DEC2AFF((Compteur_Bouton/10)%10));break;
$002A	$	L_interrupt_5:
$002A	$300A			MOVLW	10
$002B	$00F4			MOVWF	STACK_4
$002C	$0822			MOVF	_Compteur_Bouton, 0
$002D	$00F0			MOVWF	STACK_0
$002E	$2117			CALL	_div_8x8_u
$002F	$300A			MOVLW	10
$0030	$00F4			MOVWF	STACK_4
$0031	$2117			CALL	_div_8x8_u
$0032	$0878			MOVF	STACK_8, 0
$0033	$00F0			MOVWF	STACK_0
$0034	$0870			MOVF	STACK_0, 0
$0035	$00A7			MOVWF	FARG_DEC2AFF+0
$0036	$206D			CALL	_DEC2AFF
$0037	$1303			BCF	STATUS, RP1
$0038	$1283			BCF	STATUS, RP0
$0039	$0870			MOVF	STACK_0, 0
$003A	$00A7			MOVWF	FARG_AFF2+0
$003B	$2132			CALL	_AFF2
$003C	$285B			GOTO	L_interrupt_2
;tp4corig.c,52 :: 		case 3: AFF3(DEC2AFF((Compteur_Bouton/100))); break;
$003D	$	L_interrupt_6:
$003D	$3064			MOVLW	100
$003E	$00F4			MOVWF	STACK_4
$003F	$0822			MOVF	_Compteur_Bouton, 0
$0040	$00F0			MOVWF	STACK_0
$0041	$2117			CALL	_div_8x8_u
$0042	$0870			MOVF	STACK_0, 0
$0043	$00A7			MOVWF	FARG_DEC2AFF+0
$0044	$206D			CALL	_DEC2AFF
$0045	$1303			BCF	STATUS, RP1
$0046	$1283			BCF	STATUS, RP0
$0047	$0870			MOVF	STACK_0, 0
$0048	$00A7			MOVWF	FARG_AFF3+0
$0049	$2140			CALL	_AFF3
$004A	$285B			GOTO	L_interrupt_2
;tp4corig.c,53 :: 		}
$004B	$	L_interrupt_1:
$004B	$0821			MOVF	_Numero_Afficheur_Rafraichi, 0
$004C	$3A04			XORLW	4
$004D	$1903			BTFSC	STATUS, Z
$004E	$2818			GOTO	L_interrupt_3
$004F	$0821			MOVF	_Numero_Afficheur_Rafraichi, 0
$0050	$3A01			XORLW	1
$0051	$1903			BTFSC	STATUS, Z
$0052	$281A			GOTO	L_interrupt_4
$0053	$0821			MOVF	_Numero_Afficheur_Rafraichi, 0
$0054	$3A02			XORLW	2
$0055	$1903			BTFSC	STATUS, Z
$0056	$282A			GOTO	L_interrupt_5
$0057	$0821			MOVF	_Numero_Afficheur_Rafraichi, 0
$0058	$3A03			XORLW	3
$0059	$1903			BTFSC	STATUS, Z
$005A	$283D			GOTO	L_interrupt_6
$005B	$	L_interrupt_2:
;tp4corig.c,56 :: 		}
$005B	$	L_interrupt_0:
;tp4corig.c,57 :: 		if (INTCON.RBIF) {  // IT provenant d'un des boutons RB[7:4], lors
$005B	$1C0B			BTFSS	INTCON, 0
$005C	$2862			GOTO	L_interrupt_7
;tp4corig.c,61 :: 		Compteur_Bouton++;
$005D	$0AA2			INCF	_Compteur_Bouton, 1
;tp4corig.c,62 :: 		Pas_IT_sur_Maintien = PORTB;
$005E	$0806			MOVF	PORTB, 0
$005F	$00A3			MOVWF	_Pas_IT_sur_Maintien
;tp4corig.c,63 :: 		INTCON.RBIF=0;
$0060	$100B			BCF	INTCON, 0
;tp4corig.c,64 :: 		INTCON.RBIE=1;
$0061	$158B			BSF	INTCON, 3
;tp4corig.c,65 :: 		}
$0062	$	L_interrupt_7:
;tp4corig.c,66 :: 		}
$0062	$	L_Interrupt_end:
$0062	$0829			MOVF	STSAVED_0, 0
$0063	$00F0			MOVWF	STACK_0
$0064	$0826			MOVF	?savePCLATH, 0
$0065	$008A			MOVWF	PCLATH
$0066	$0824			MOVF	?saveFSR, 0
$0067	$0084			MOVWF	FSR
$0068	$0E25			SWAPF	?saveSTATUS, 0
$0069	$0083			MOVWF	STATUS
$006A	$0EFF			SWAPF	STACK_15, 1
$006B	$0E7F			SWAPF	STACK_15, 0
$006C	$0009			RETFIE
$0147	$	_LED_C_Init:
;bibliotheque.c,52 :: 		void LED_C_Init(void)
;bibliotheque.c,54 :: 		TRISC = 0x00;  // Initialisation du port B en sortie
$0147	$1303			BCF	STATUS, RP1
$0148	$1683			BSF	STATUS, RP0
$0149	$0187			CLRF	TRISC, 1
;bibliotheque.c,55 :: 		PORTC = 0;     // Extinction des Leds
$014A	$1283			BCF	STATUS, RP0
$014B	$0187			CLRF	PORTC, 1
;bibliotheque.c,56 :: 		}
$014C	$0008			RETURN
$014D	$	_LED_C:
;bibliotheque.c,122 :: 		void LED_C(unsigned char Value)
;bibliotheque.c,124 :: 		PORTC = Value;
$014D	$1303			BCF	STATUS, RP1
$014E	$1283			BCF	STATUS, RP0
$014F	$0828			MOVF	FARG_LED_C+0, 0
$0150	$0087			MOVWF	PORTC
;bibliotheque.c,125 :: 		}
$0151	$0008			RETURN
$0128	$	_AFF_Init:
;bibliotheque.c,38 :: 		void AFF_Init(void)
;bibliotheque.c,40 :: 		TRISA = 0x00;  // Initialisation du port A en sortie
$0128	$1303			BCF	STATUS, RP1
$0129	$1683			BSF	STATUS, RP0
$012A	$0185			CLRF	TRISA, 1
;bibliotheque.c,41 :: 		PORTA = 0;     // A = numéro d'afficheur (entre 1 et 4)
$012B	$1283			BCF	STATUS, RP0
$012C	$0185			CLRF	PORTA, 1
;bibliotheque.c,42 :: 		TRISD = 0x00;  // Initialisation du port D en sortie
$012D	$1683			BSF	STATUS, RP0
$012E	$0188			CLRF	TRISD, 1
;bibliotheque.c,43 :: 		PORTD = 0;     // D = valeur (cathode commune) a afficher
$012F	$1283			BCF	STATUS, RP0
$0130	$0188			CLRF	PORTD, 1
;bibliotheque.c,44 :: 		}
$0131	$0008			RETURN
$00F7	$	_main:
;tp4corig.c,68 :: 		void main() {
;tp4corig.c,71 :: 		OPTION_REG = 0;
$00F7	$1303			BCF	STATUS, RP1
$00F8	$1683			BSF	STATUS, RP0
$00F9	$0181			CLRF	OPTION_REG, 1
;tp4corig.c,72 :: 		INTCON=0;
$00FA	$018B			CLRF	INTCON, 1
;tp4corig.c,76 :: 		OPTION_REG |= 0b00000001;
$00FB	$3001			MOVLW	1
$00FC	$0081			MOVWF	OPTION_REG
;tp4corig.c,77 :: 		TMR0=0x20;
$00FD	$3020			MOVLW	32
$00FE	$1283			BCF	STATUS, RP0
$00FF	$0081			MOVWF	TMR0
;tp4corig.c,78 :: 		INTCON |= 0x20;
$0100	$168B			BSF	INTCON, 5
;tp4corig.c,79 :: 		OPTION_REG.NOT_RBPU = 1;
$0101	$1683			BSF	STATUS, RP0
$0102	$1781			BSF	OPTION_REG, 7
;tp4corig.c,80 :: 		TRISB = 0b11110000;
$0103	$30F0			MOVLW	240
$0104	$0086			MOVWF	TRISB
;tp4corig.c,81 :: 		INTCON |= 0x08;
$0105	$158B			BSF	INTCON, 3
;tp4corig.c,86 :: 		Compteur_Temps = 0;
$0106	$1283			BCF	STATUS, RP0
$0107	$01A0			CLRF	_Compteur_Temps, 1
;tp4corig.c,87 :: 		Compteur_Bouton = 0;
$0108	$01A2			CLRF	_Compteur_Bouton, 1
;tp4corig.c,88 :: 		Numero_Afficheur_Rafraichi=0;
$0109	$01A1			CLRF	_Numero_Afficheur_Rafraichi, 1
;tp4corig.c,91 :: 		LED_C_Init();
$010A	$2147			CALL	_LED_C_Init
;tp4corig.c,92 :: 		LED_C(0xAA);
$010B	$30AA			MOVLW	170
$010C	$00A8			MOVWF	FARG_LED_C+0
$010D	$214D			CALL	_LED_C
;tp4corig.c,93 :: 		AFF_Init();
$010E	$2128			CALL	_AFF_Init
;tp4corig.c,95 :: 		INTCON.GIE = 1;
$010F	$178B			BSF	INTCON, 7
;tp4corig.c,96 :: 		while(1) {
$0110	$	L_main_8:
;tp4corig.c,97 :: 		if (Compteur_Temps==0xFF) {
$0110	$0820			MOVF	_Compteur_Temps, 0
$0111	$3AFF			XORLW	255
$0112	$1D03			BTFSS	STATUS, Z
$0113	$2915			GOTO	L_main_10
;tp4corig.c,100 :: 		Compteur_Temps = 0;
$0114	$01A0			CLRF	_Compteur_Temps, 1
;tp4corig.c,101 :: 		}
$0115	$	L_main_10:
;tp4corig.c,102 :: 		}
$0115	$2910			GOTO	L_main_8
;tp4corig.c,103 :: 		}
$0116	$2916			GOTO	$
