#makefile pour tout les compilateurs

#compilateur
CC = gcc
#options de compilation
OPT = -Wall -ansi -pedantic
#liste des fichiers objets 
OBJ = tp1.o
#regle de production finale tp:
tp1 : $(OBJ)
	$(CC) $(OBJ) -o tp1
#regle de nettoyage
clean : 
	rm *.o 

