//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.1
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBook.ServiceIsimaServ {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Book", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Book : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ReleaseDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebBook.ServiceIsimaServ.Author WriterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameWriterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebBook.ServiceIsimaServ.Editor PublisherField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WebBook.ServiceIsimaServ.Kind TypeField;
        
        private double PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ReleaseDate {
            get {
                return this.ReleaseDateField;
            }
            set {
                if ((object.ReferenceEquals(this.ReleaseDateField, value) != true)) {
                    this.ReleaseDateField = value;
                    this.RaisePropertyChanged("ReleaseDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public WebBook.ServiceIsimaServ.Author Writer {
            get {
                return this.WriterField;
            }
            set {
                if ((object.ReferenceEquals(this.WriterField, value) != true)) {
                    this.WriterField = value;
                    this.RaisePropertyChanged("Writer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string NameWriter {
            get {
                return this.NameWriterField;
            }
            set {
                if ((object.ReferenceEquals(this.NameWriterField, value) != true)) {
                    this.NameWriterField = value;
                    this.RaisePropertyChanged("NameWriter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WebBook.ServiceIsimaServ.Editor Publisher {
            get {
                return this.PublisherField;
            }
            set {
                if ((object.ReferenceEquals(this.PublisherField, value) != true)) {
                    this.PublisherField = value;
                    this.RaisePropertyChanged("Publisher");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WebBook.ServiceIsimaServ.Kind Type {
            get {
                return this.TypeField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeField, value) != true)) {
                    this.TypeField = value;
                    this.RaisePropertyChanged("Type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public double Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Author", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Author : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Editor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Editor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Kind", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Kind : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GUIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string GUID {
            get {
                return this.GUIDField;
            }
            set {
                if ((object.ReferenceEquals(this.GUIDField, value) != true)) {
                    this.GUIDField = value;
                    this.RaisePropertyChanged("GUID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ContactDetails", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class ContactDetails : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ZipcodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Adress {
            get {
                return this.AdressField;
            }
            set {
                if ((object.ReferenceEquals(this.AdressField, value) != true)) {
                    this.AdressField = value;
                    this.RaisePropertyChanged("Adress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Zipcode {
            get {
                return this.ZipcodeField;
            }
            set {
                if ((object.ReferenceEquals(this.ZipcodeField, value) != true)) {
                    this.ZipcodeField = value;
                    this.RaisePropertyChanged("Zipcode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Currency", Namespace="http://www.webserviceX.NET/")]
    public enum Currency : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AFA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ALL = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DZD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ARS = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AWG = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AUD = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BSD = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BHD = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BDT = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BBD = 9,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BZD = 10,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BMD = 11,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BTN = 12,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BOB = 13,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BWP = 14,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BRL = 15,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GBP = 16,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BND = 17,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        BIF = 18,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XOF = 19,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAF = 20,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KHR = 21,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CAD = 22,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CVE = 23,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KYD = 24,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CLP = 25,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNY = 26,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        COP = 27,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KMF = 28,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CRC = 29,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HRK = 30,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CUP = 31,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CYP = 32,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CZK = 33,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DKK = 34,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DJF = 35,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DOP = 36,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XCD = 37,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EGP = 38,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SVC = 39,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EEK = 40,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ETB = 41,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EUR = 42,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        FKP = 43,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GMD = 44,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GHC = 45,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GIP = 46,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAU = 47,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GTQ = 48,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GNF = 49,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GYD = 50,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HTG = 51,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HNL = 52,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HKD = 53,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HUF = 54,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ISK = 55,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        INR = 56,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IDR = 57,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IQD = 58,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ILS = 59,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JMD = 60,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JPY = 61,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        JOD = 62,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KZT = 63,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KES = 64,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KRW = 65,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KWD = 66,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LAK = 67,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LVL = 68,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LBP = 69,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LSL = 70,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LRD = 71,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LYD = 72,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LTL = 73,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MOP = 74,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MKD = 75,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MGF = 76,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MWK = 77,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MYR = 78,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MVR = 79,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MTL = 80,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MRO = 81,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MUR = 82,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MXN = 83,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MDL = 84,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MNT = 85,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MAD = 86,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MZM = 87,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MMK = 88,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NAD = 89,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NPR = 90,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ANG = 91,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NZD = 92,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NIO = 93,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NGN = 94,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        KPW = 95,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NOK = 96,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OMR = 97,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPF = 98,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PKR = 99,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPD = 100,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PAB = 101,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PGK = 102,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PYG = 103,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PEN = 104,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PHP = 105,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XPT = 106,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PLN = 107,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        QAR = 108,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ROL = 109,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        RUB = 110,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        WST = 111,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        STD = 112,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SAR = 113,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SCR = 114,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SLL = 115,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        XAG = 116,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SGD = 117,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SKK = 118,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SIT = 119,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SBD = 120,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SOS = 121,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZAR = 122,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        LKR = 123,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SHP = 124,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SDD = 125,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SRG = 126,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SZL = 127,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SEK = 128,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CHF = 129,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SYP = 130,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TWD = 131,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TZS = 132,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        THB = 133,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TOP = 134,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TTD = 135,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TND = 136,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRL = 137,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        USD = 138,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        AED = 139,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UGX = 140,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UAH = 141,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        UYU = 142,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VUV = 143,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VEB = 144,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        VND = 145,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YER = 146,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        YUM = 147,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZMK = 148,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ZWD = 149,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TRY = 150,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceIsimaServ.ServiceIsimaBookSoap")]
    public interface ServiceIsimaBookSoap {
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément HelloWorldResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WebBook.ServiceIsimaServ.HelloWorldResponse HelloWorld(WebBook.ServiceIsimaServ.HelloWorldRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément username de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RegisterOrder", ReplyAction="*")]
        WebBook.ServiceIsimaServ.RegisterOrderResponse RegisterOrder(WebBook.ServiceIsimaServ.RegisterOrderRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément creditcard de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyCreditCard", ReplyAction="*")]
        WebBook.ServiceIsimaServ.VerifyCreditCardResponse VerifyCreditCard(WebBook.ServiceIsimaServ.VerifyCreditCardRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément AllBooksResult de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllBooks", ReplyAction="*")]
        WebBook.ServiceIsimaServ.AllBooksResponse AllBooks(WebBook.ServiceIsimaServ.AllBooksRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément writer de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookByWriter", ReplyAction="*")]
        WebBook.ServiceIsimaServ.BookByWriterResponse BookByWriter(WebBook.ServiceIsimaServ.BookByWriterRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément title de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookByTitle", ReplyAction="*")]
        WebBook.ServiceIsimaServ.BookByTitleResponse BookByTitle(WebBook.ServiceIsimaServ.BookByTitleRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément GUID de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BookByGUID", ReplyAction="*")]
        WebBook.ServiceIsimaServ.BookByGUIDResponse BookByGUID(WebBook.ServiceIsimaServ.BookByGUIDRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément username de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddUser", ReplyAction="*")]
        WebBook.ServiceIsimaServ.AddUserResponse AddUser(WebBook.ServiceIsimaServ.AddUserRequest request);
        
        // CODEGEN : La génération du contrat de message depuis le nom d'élément username de l'espace de noms http://tempuri.org/ n'est pas marqué nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VerifyUser", ReplyAction="*")]
        WebBook.ServiceIsimaServ.VerifyUserResponse VerifyUser(WebBook.ServiceIsimaServ.VerifyUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConvertEuroTo", ReplyAction="*")]
        double ConvertEuroTo(double europrice, WebBook.ServiceIsimaServ.Currency exchange);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WebBook.ServiceIsimaServ.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WebBook.ServiceIsimaServ.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterOrder", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.RegisterOrderRequestBody Body;
        
        public RegisterOrderRequest() {
        }
        
        public RegisterOrderRequest(WebBook.ServiceIsimaServ.RegisterOrderRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterOrderRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public WebBook.ServiceIsimaServ.Book[] books;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string creditcard;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WebBook.ServiceIsimaServ.ContactDetails shipping;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WebBook.ServiceIsimaServ.ContactDetails invoicing;
        
        public RegisterOrderRequestBody() {
        }
        
        public RegisterOrderRequestBody(string username, WebBook.ServiceIsimaServ.Book[] books, string creditcard, WebBook.ServiceIsimaServ.ContactDetails shipping, WebBook.ServiceIsimaServ.ContactDetails invoicing) {
            this.username = username;
            this.books = books;
            this.creditcard = creditcard;
            this.shipping = shipping;
            this.invoicing = invoicing;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterOrderResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.RegisterOrderResponseBody Body;
        
        public RegisterOrderResponse() {
        }
        
        public RegisterOrderResponse(WebBook.ServiceIsimaServ.RegisterOrderResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class RegisterOrderResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RegisterOrderResult;
        
        public RegisterOrderResponseBody() {
        }
        
        public RegisterOrderResponseBody(string RegisterOrderResult) {
            this.RegisterOrderResult = RegisterOrderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCreditCardRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyCreditCard", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.VerifyCreditCardRequestBody Body;
        
        public VerifyCreditCardRequest() {
        }
        
        public VerifyCreditCardRequest(WebBook.ServiceIsimaServ.VerifyCreditCardRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyCreditCardRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string creditcard;
        
        public VerifyCreditCardRequestBody() {
        }
        
        public VerifyCreditCardRequestBody(string creditcard) {
            this.creditcard = creditcard;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyCreditCardResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyCreditCardResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.VerifyCreditCardResponseBody Body;
        
        public VerifyCreditCardResponse() {
        }
        
        public VerifyCreditCardResponse(WebBook.ServiceIsimaServ.VerifyCreditCardResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyCreditCardResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyCreditCardResult;
        
        public VerifyCreditCardResponseBody() {
        }
        
        public VerifyCreditCardResponseBody(bool VerifyCreditCardResult) {
            this.VerifyCreditCardResult = VerifyCreditCardResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllBooksRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllBooks", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.AllBooksRequestBody Body;
        
        public AllBooksRequest() {
        }
        
        public AllBooksRequest(WebBook.ServiceIsimaServ.AllBooksRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AllBooksRequestBody {
        
        public AllBooksRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AllBooksResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AllBooksResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.AllBooksResponseBody Body;
        
        public AllBooksResponse() {
        }
        
        public AllBooksResponse(WebBook.ServiceIsimaServ.AllBooksResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AllBooksResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBook.ServiceIsimaServ.Book[] AllBooksResult;
        
        public AllBooksResponseBody() {
        }
        
        public AllBooksResponseBody(WebBook.ServiceIsimaServ.Book[] AllBooksResult) {
            this.AllBooksResult = AllBooksResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookByWriterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookByWriter", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.BookByWriterRequestBody Body;
        
        public BookByWriterRequest() {
        }
        
        public BookByWriterRequest(WebBook.ServiceIsimaServ.BookByWriterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookByWriterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string writer;
        
        public BookByWriterRequestBody() {
        }
        
        public BookByWriterRequestBody(string writer) {
            this.writer = writer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookByWriterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookByWriterResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.BookByWriterResponseBody Body;
        
        public BookByWriterResponse() {
        }
        
        public BookByWriterResponse(WebBook.ServiceIsimaServ.BookByWriterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookByWriterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBook.ServiceIsimaServ.Book[] BookByWriterResult;
        
        public BookByWriterResponseBody() {
        }
        
        public BookByWriterResponseBody(WebBook.ServiceIsimaServ.Book[] BookByWriterResult) {
            this.BookByWriterResult = BookByWriterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookByTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookByTitle", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.BookByTitleRequestBody Body;
        
        public BookByTitleRequest() {
        }
        
        public BookByTitleRequest(WebBook.ServiceIsimaServ.BookByTitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookByTitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public BookByTitleRequestBody() {
        }
        
        public BookByTitleRequestBody(string title) {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookByTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookByTitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.BookByTitleResponseBody Body;
        
        public BookByTitleResponse() {
        }
        
        public BookByTitleResponse(WebBook.ServiceIsimaServ.BookByTitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookByTitleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBook.ServiceIsimaServ.Book[] BookByTitleResult;
        
        public BookByTitleResponseBody() {
        }
        
        public BookByTitleResponseBody(WebBook.ServiceIsimaServ.Book[] BookByTitleResult) {
            this.BookByTitleResult = BookByTitleResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookByGUIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookByGUID", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.BookByGUIDRequestBody Body;
        
        public BookByGUIDRequest() {
        }
        
        public BookByGUIDRequest(WebBook.ServiceIsimaServ.BookByGUIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookByGUIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GUID;
        
        public BookByGUIDRequestBody() {
        }
        
        public BookByGUIDRequestBody(string GUID) {
            this.GUID = GUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BookByGUIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BookByGUIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.BookByGUIDResponseBody Body;
        
        public BookByGUIDResponse() {
        }
        
        public BookByGUIDResponse(WebBook.ServiceIsimaServ.BookByGUIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BookByGUIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebBook.ServiceIsimaServ.Book BookByGUIDResult;
        
        public BookByGUIDResponseBody() {
        }
        
        public BookByGUIDResponseBody(WebBook.ServiceIsimaServ.Book BookByGUIDResult) {
            this.BookByGUIDResult = BookByGUIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(WebBook.ServiceIsimaServ.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string adress;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string zipcode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string city;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string password;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string username, string adress, string zipcode, string city, string password) {
            this.username = username;
            this.adress = adress;
            this.zipcode = zipcode;
            this.city = city;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(WebBook.ServiceIsimaServ.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(bool AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyUser", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.VerifyUserRequestBody Body;
        
        public VerifyUserRequest() {
        }
        
        public VerifyUserRequest(WebBook.ServiceIsimaServ.VerifyUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public VerifyUserRequestBody() {
        }
        
        public VerifyUserRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VerifyUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VerifyUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public WebBook.ServiceIsimaServ.VerifyUserResponseBody Body;
        
        public VerifyUserResponse() {
        }
        
        public VerifyUserResponse(WebBook.ServiceIsimaServ.VerifyUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VerifyUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool VerifyUserResult;
        
        public VerifyUserResponseBody() {
        }
        
        public VerifyUserResponseBody(bool VerifyUserResult) {
            this.VerifyUserResult = VerifyUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceIsimaBookSoapChannel : WebBook.ServiceIsimaServ.ServiceIsimaBookSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceIsimaBookSoapClient : System.ServiceModel.ClientBase<WebBook.ServiceIsimaServ.ServiceIsimaBookSoap>, WebBook.ServiceIsimaServ.ServiceIsimaBookSoap {
        
        public ServiceIsimaBookSoapClient() {
        }
        
        public ServiceIsimaBookSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceIsimaBookSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIsimaBookSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceIsimaBookSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBook.ServiceIsimaServ.HelloWorldResponse WebBook.ServiceIsimaServ.ServiceIsimaBookSoap.HelloWorld(WebBook.ServiceIsimaServ.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WebBook.ServiceIsimaServ.HelloWorldRequest inValue = new WebBook.ServiceIsimaServ.HelloWorldRequest();
            inValue.Body = new WebBook.ServiceIsimaServ.HelloWorldRequestBody();
            WebBook.ServiceIsimaServ.HelloWorldResponse retVal = ((WebBook.ServiceIsimaServ.ServiceIsimaBookSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBook.ServiceIsimaServ.RegisterOrderResponse WebBook.ServiceIsimaServ.ServiceIsimaBookSoap.RegisterOrder(WebBook.ServiceIsimaServ.RegisterOrderRequest request) {
            return base.Channel.RegisterOrder(request);
        }
        
        public string RegisterOrder(string username, WebBook.ServiceIsimaServ.Book[] books, string creditcard, WebBook.ServiceIsimaServ.ContactDetails shipping, WebBook.ServiceIsimaServ.ContactDetails invoicing) {
            WebBook.ServiceIsimaServ.RegisterOrderRequest inValue = new WebBook.ServiceIsimaServ.RegisterOrderRequest();
            inValue.Body = new WebBook.ServiceIsimaServ.RegisterOrderRequestBody();
            inValue.Body.username = username;
            inValue.Body.books = books;
            inValue.Body.creditcard = creditcard;
            inValue.Body.shipping = shipping;
            inValue.Body.invoicing = invoicing;
            WebBook.ServiceIsimaServ.RegisterOrderResponse retVal = ((WebBook.ServiceIsimaServ.ServiceIsimaBookSoap)(this)).RegisterOrder(inValue);
            return retVal.Body.RegisterOrderResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBook.ServiceIsimaServ.VerifyCreditCardResponse WebBook.ServiceIsimaServ.ServiceIsimaBookSoap.VerifyCreditCard(WebBook.ServiceIsimaServ.VerifyCreditCardRequest request) {
            return base.Channel.VerifyCreditCard(request);
        }
        
        public bool VerifyCreditCard(string creditcard) {
            WebBook.ServiceIsimaServ.VerifyCreditCardRequest inValue = new WebBook.ServiceIsimaServ.VerifyCreditCardRequest();
            inValue.Body = new WebBook.ServiceIsimaServ.VerifyCreditCardRequestBody();
            inValue.Body.creditcard = creditcard;
            WebBook.ServiceIsimaServ.VerifyCreditCardResponse retVal = ((WebBook.ServiceIsimaServ.ServiceIsimaBookSoap)(this)).VerifyCreditCard(inValue);
            return retVal.Body.VerifyCreditCardResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBook.ServiceIsimaServ.AllBooksResponse WebBook.ServiceIsimaServ.ServiceIsimaBookSoap.AllBooks(WebBook.ServiceIsimaServ.AllBooksRequest request) {
            return base.Channel.AllBooks(request);
        }
        
        public WebBook.ServiceIsimaServ.Book[] AllBooks() {
            WebBook.ServiceIsimaServ.AllBooksRequest inValue = new WebBook.ServiceIsimaServ.AllBooksRequest();
            inValue.Body = new WebBook.ServiceIsimaServ.AllBooksRequestBody();
            WebBook.ServiceIsimaServ.AllBooksResponse retVal = ((WebBook.ServiceIsimaServ.ServiceIsimaBookSoap)(this)).AllBooks(inValue);
            return retVal.Body.AllBooksResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBook.ServiceIsimaServ.BookByWriterResponse WebBook.ServiceIsimaServ.ServiceIsimaBookSoap.BookByWriter(WebBook.ServiceIsimaServ.BookByWriterRequest request) {
            return base.Channel.BookByWriter(request);
        }
        
        public WebBook.ServiceIsimaServ.Book[] BookByWriter(string writer) {
            WebBook.ServiceIsimaServ.BookByWriterRequest inValue = new WebBook.ServiceIsimaServ.BookByWriterRequest();
            inValue.Body = new WebBook.ServiceIsimaServ.BookByWriterRequestBody();
            inValue.Body.writer = writer;
            WebBook.ServiceIsimaServ.BookByWriterResponse retVal = ((WebBook.ServiceIsimaServ.ServiceIsimaBookSoap)(this)).BookByWriter(inValue);
            return retVal.Body.BookByWriterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBook.ServiceIsimaServ.BookByTitleResponse WebBook.ServiceIsimaServ.ServiceIsimaBookSoap.BookByTitle(WebBook.ServiceIsimaServ.BookByTitleRequest request) {
            return base.Channel.BookByTitle(request);
        }
        
        public WebBook.ServiceIsimaServ.Book[] BookByTitle(string title) {
            WebBook.ServiceIsimaServ.BookByTitleRequest inValue = new WebBook.ServiceIsimaServ.BookByTitleRequest();
            inValue.Body = new WebBook.ServiceIsimaServ.BookByTitleRequestBody();
            inValue.Body.title = title;
            WebBook.ServiceIsimaServ.BookByTitleResponse retVal = ((WebBook.ServiceIsimaServ.ServiceIsimaBookSoap)(this)).BookByTitle(inValue);
            return retVal.Body.BookByTitleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBook.ServiceIsimaServ.BookByGUIDResponse WebBook.ServiceIsimaServ.ServiceIsimaBookSoap.BookByGUID(WebBook.ServiceIsimaServ.BookByGUIDRequest request) {
            return base.Channel.BookByGUID(request);
        }
        
        public WebBook.ServiceIsimaServ.Book BookByGUID(string GUID) {
            WebBook.ServiceIsimaServ.BookByGUIDRequest inValue = new WebBook.ServiceIsimaServ.BookByGUIDRequest();
            inValue.Body = new WebBook.ServiceIsimaServ.BookByGUIDRequestBody();
            inValue.Body.GUID = GUID;
            WebBook.ServiceIsimaServ.BookByGUIDResponse retVal = ((WebBook.ServiceIsimaServ.ServiceIsimaBookSoap)(this)).BookByGUID(inValue);
            return retVal.Body.BookByGUIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBook.ServiceIsimaServ.AddUserResponse WebBook.ServiceIsimaServ.ServiceIsimaBookSoap.AddUser(WebBook.ServiceIsimaServ.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public bool AddUser(string username, string adress, string zipcode, string city, string password) {
            WebBook.ServiceIsimaServ.AddUserRequest inValue = new WebBook.ServiceIsimaServ.AddUserRequest();
            inValue.Body = new WebBook.ServiceIsimaServ.AddUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.adress = adress;
            inValue.Body.zipcode = zipcode;
            inValue.Body.city = city;
            inValue.Body.password = password;
            WebBook.ServiceIsimaServ.AddUserResponse retVal = ((WebBook.ServiceIsimaServ.ServiceIsimaBookSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebBook.ServiceIsimaServ.VerifyUserResponse WebBook.ServiceIsimaServ.ServiceIsimaBookSoap.VerifyUser(WebBook.ServiceIsimaServ.VerifyUserRequest request) {
            return base.Channel.VerifyUser(request);
        }
        
        public bool VerifyUser(string username, string password) {
            WebBook.ServiceIsimaServ.VerifyUserRequest inValue = new WebBook.ServiceIsimaServ.VerifyUserRequest();
            inValue.Body = new WebBook.ServiceIsimaServ.VerifyUserRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            WebBook.ServiceIsimaServ.VerifyUserResponse retVal = ((WebBook.ServiceIsimaServ.ServiceIsimaBookSoap)(this)).VerifyUser(inValue);
            return retVal.Body.VerifyUserResult;
        }
        
        public double ConvertEuroTo(double europrice, WebBook.ServiceIsimaServ.Currency exchange) {
            return base.Channel.ConvertEuroTo(europrice, exchange);
        }
    }
}
